CREATE STREAM ACCELEROMETER
(DUID VARCHAR KEY,
AMOUNT DOUBLE)
WITH (
KAFKA_TOPIC='accelerometer',
KEY_FORMAT='kafka',
VALUE_FORMAT='avro',
PARTITIONS=1);

CREATE STREAM GYROSCOPE
(DUID VARCHAR KEY,
AMOUNT DOUBLE)
WITH (
KAFKA_TOPIC='gyroscope',
KEY_FORMAT='kafka',
VALUE_FORMAT='avro',
PARTITIONS=1);

CREATE STREAM ACC_GYR_JOIN
WITH (
KAFKA_TOPIC='acc_gyr_join',
KEY_FORMAT='kafka',
VALUE_FORMAT='avro',
PARTITIONS=1)
AS
SELECT A.DUID DUID, A.AMOUNT A_AMOUNT, G.AMOUNT G_AMOUNT
FROM ACCELEROMETER A
INNER JOIN GYROSCOPE G WITHIN 1 MILLISECONDS
ON ((A.DUID = G.DUID));

CREATE TABLE CRASH_CHECK
WITH (
KAFKA_TOPIC='crash_check',
KEY_FORMAT='kafka',
VALUE_FORMAT='avro',
PARTITIONS=1)
AS
SELECT DUID, ACC_CRASH_CONDITION(A_AMOUNT) ACC_CRASH, GYR_CRASH_CONDITION(G_AMOUNT) GYR_CRASH
FROM ACC_GYR_JOIN
WINDOW TUMBLING (SIZE 1 SECONDS)
GROUP BY DUID;
