CREATE STREAM ACCELEROMETER
(DUID VARCHAR KEY,
AMOUNT DOUBLE)
WITH (
KAFKA_TOPIC='accelerometer',
KEY_FORMAT='kafka',
VALUE_FORMAT='avro',
PARTITIONS=1);

CREATE STREAM GYROSCOPE
(DUID VARCHAR KEY,
AMOUNT DOUBLE)
WITH (
KAFKA_TOPIC='gyroscope',
KEY_FORMAT='kafka',
VALUE_FORMAT='avro',
PARTITIONS=1);

CREATE TABLE CRASH
WITH (
KAFKA_TOPIC='crash',
KEY_FORMAT='avro',
VALUE_FORMAT='avro',
PARTITIONS=1)
AS
SELECT FROM_UNIXTIME(MAX(A.ROWTIME)) CRASHTIME, A.DUID DUID, AVG(A.AMOUNT) A_AMOUNT, AVG(G.AMOUNT) G_AMOUNT
FROM ACCELEROMETER A
INNER JOIN GYROSCOPE G WITHIN 2 MILLISECONDS
ON ((A.DUID = G.DUID))
GROUP BY A.DUID
EMIT CHANGES;
